version: '3'

services:
  fastapi-service:
    build: ./server
    depends_on:
      - mongo-service
    ports:
      - 8000:8000
    networks:
      - ocr-net
    container_name: fastapi-cont

  streamlit-service:
    build: ./client
    depends_on:
      - fastapi-service
    ports:
      - 8501:8501
    networks:
      - ocr-net
    container_name: streamlit-cont

  mongo-service:
    build: ./database
    ports:
      - 27017:27017
    networks:
      - ocr-net
    container_name: mongo-cont


networks:
  ocr-net:
    driver: bridge



